name: Cancel
on:
  workflow_run:
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    if: github.repository != 'gautamkrishnar/github-pages-gallery'
    steps:
     - uses: styfle/cancel-workflow-action@0.9.0
       with:
         workflow_id: ${{ github.event.workflow.id }}
